### ISSUE TITLE
How to apply MQL to my own environment?

### ISSUE THREAD

**Issue by SARAtsu** [amazon-research/meta-q-learning#1]
Hello, I really appreciate for this great work. I'd like to ask how can i quickly apply MQL to my own environment to see the performance? Is it a right way that register my environment and define ```step```, ```sample_tasks``` functions? Beside, why there is not ```reset``` function in many environments? 

Thanks a lot.

**Comment by rasoolfa** [comment]
Hi,
Yes, you need to register your new environment and add required functions in order to be able to use MQL. There is reset and  it inherits from gym/mujoco for most of the envs.
