### ISSUE TITLE
Different Context Variables for Actor and Critic

### ISSUE THREAD

**Issue by XyDrKRulof** [amazon-research/meta-q-learning#3]
Hello there,

in your paper you state that you have a context-variable z_t which is then fed into the actor and critic networks of the TD3-algorithm. However, in your code it looks like actor and critic have different initializations of the context network. That means the weights of them will not be the same. 

Additionally, if we also count the target actor and ciritc, we do have 4 differently parametrized context networks . From my understanding of your paper we would like to have one context network which feeds the context variable z_t into the actor and critic networks. As from how the code currently looks I figure we don't have one context z_t but 2 or 4 different context variables z1_t - z4_t.

Am I missing something here? What was the reasoning behind directly adding the recurrent context network into the actor and critic architectures rather than having you own context network which shares weights for critic and actor?

**Comment by rasoolfa** [comment]
Hi,

Even though MQL is agnostic to the type of off-policy method, in this paper, MQL was implemented on top of TD3 which has 2 q-networks (i.e. Q_\phi_1, Q_\phi_2) and one policy (\pi_\theta) network ( and targets networks which are a few steps behind current q-networks). For the ease of implementation and minimal changes to TD3 algorithm, we used 2 context networks for each Q and one for the policy network. Note to emphasize the general idea of MQL( i.e. multi-task learning objective + context + adaption), we only discussed one q-network throughout the paper (except briefly on page 4) and we didn't limit the design choice of context network in case of multiple q-network.

Hope that helps.

**Comment by desaixie** [comment]
Hi,

Same question here. Could you explain, under the TD3 algorithm, what are the benefits of using separate context networks over letting the actor and the two Q networks share the same context network? Did you experimentally compare the two designs? Thanks.
