### ISSUE TITLE
TD3-Context

### ISSUE THREAD

**Issue by nil123532** [amazon-research/meta-q-learning#6]
Hello, 
I am trying to reproduce results for vanilla TD3-context. 

The paper does not really go into details on how vanilla TD3-context is implemented and neither does the code. 

How do i do so?

**Comment by nil123532** [comment]
oh wait - would disabling "adaptation phase" result in training TD3-Context?

**Comment by rasoolfa** [comment]
yes. no adaption, means TD3-context. 
TD3-context extends TD3 by incorporating a context variable z  into both the Q-value and policy functions:  Q(s, a) becomes  Q(s, a, z)  and \pi(a | s)  becomes \pi(a | s, z). There’s no need to change the objective functions. To learn z , you can use a GRU, LSTM, or Transformer to encode a sequence of (s_0, a_0, r_0, ..., s_t, a_t, r_t) and its parameters will be learned by doing standard TD3 objectives.  

Also, check out this https://github.com/twni2016/pomdp-baselines  follow up paper that studies in depth different context variables and have various implementations (with SAC as well).

**Comment by nil123532** [comment]
Thanks a ton!
